### ISSUE TITLE
Plugin crashed on for loop (for (i in 0.ii))

### ISSUE THREAD

**Issue by andrew-git** [SlavaRa/fdplugin-postfix-code-completion#83]
If in for loop set arguments and then add point(first or second between them) plugin crashes
`for (i in 0.ii)`
`for (i in 0 .ii)`
`for (i in 0 . ii)`

FD 5.3.4.594
PostfixCodeCompletion 2.0.14

> ************** Exception Text **************
System.Reflection.AmbiguousMatchException: Ambiguous match found.
   at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetMethod(String name, BindingFlags bindingAttr)
   at PostfixCodeCompletion.Helpers.ASCompleteReflector.HandleDotCompletion(ScintillaControl sci, Boolean autoHide)
   at PostfixCodeCompletion.Completion.PCCASComplete.OnCharAdded(Int32 value)
   at PostfixCodeCompletion.Completion.Complete.OnCharAdded(Int32 value)
   at PostfixCodeCompletion.PluginMain.<>c.<AddEventHandlers>b__22_0(ScintillaControl _, Int32 value)
   at PluginCore.Controls.UITools.CharAddedHandler.Invoke(ScintillaControl sender, Int32 value)
   at PluginCore.Controls.UITools.SendChar(ScintillaControl sci, Int32 value)
   at PluginCore.Controls.UITools.OnChar(ScintillaControl sci, Int32 value)
   at ScintillaNet.CharAddedHandler.Invoke(ScintillaControl sender, Int32 ch)
   at ScintillaNet.ScintillaControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by andrew-git** [comment]
Appears even on
`for (i in 0 .`
`var f : Float = 0.`
